spring:
  application:
    name: myshop-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: http://git.ubuntu.com:8088/myshop/myshop-config-respo.git
          search-paths: respo
          username: develop
          password: 12345678

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"