spring:
  application:
    name: myshop-eureka
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"