spring:
  cloud:
    config:
      uri: http://git.ubuntu.com:8888/
      label: master
      name: myshop-service-admin,myshop-client-eureka,myshop-client-admin,myshop-client-zipkin
      profile: prod